### ISSUE TITLE
PoshSNMP can not file an Issue

### ISSUE THREAD

**Issue by Kriegel** [JustinGrote/PoshNmap#12]
Hi!

I found no Email nor I can file an Issue for the PoshSNMP repository.
Is this intended ??

**Comment by JustinGrote** [comment]
@Kriegel I don't think I've touched that Repo in years, it can probably be considered dead. You can take the existing module and update it though. There's lots of other SNMP modules out there too.

**Comment by Kriegel** [comment]
@JustinGrote Thank you for clarification!

> There's lots of other SNMP modules out there too.

Yes, but not .NET Core able ...
