### ISSUE TITLE
Problems running Poshnmap with the new version of nmap

### ISSUE THREAD

**Issue by fjvasquez** [JustinGrote/PoshNmap#13]
When I try to run the command invoke-nmap www.google.com there is an error about Sytem.object not being able to be converted to xml objects.

**Comment by JustinGrote** [comment]
Hi, can you tell me which version of PS and nmap you are on?

**Comment by fjvasquez** [comment]
Powershell: 7.1.5
Nmap: 7.92

**Comment by JustinGrote** [comment]
I'll give it a review when I get a chance.

**Comment by fjvasquez** [comment]
Thanks.

**Comment by JustinGrote** [comment]
I can reproduce, I didn't have the latest installed. Looks like they changed the XML format
![image](https://user-images.githubusercontent.com/15258962/140375599-afaa6351-cbcd-415c-abf6-76bb464b71a3.png)

**Comment by JustinGrote** [comment]
@fjvasquez this should be fixed in 0.6.1, I'm closing, please comment here if it still doesn't work for you.
